// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_meta.sql

package db

import (
	"context"
)

const getAppMeta = `-- name: GetAppMeta :one
SELECT key, value, updated_at
FROM app_meta
WHERE key = $1
`

func (q *Queries) GetAppMeta(ctx context.Context, key string) (AppMeta, error) {
	row := q.db.QueryRow(ctx, getAppMeta, key)
	var i AppMeta
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const setAppMeta = `-- name: SetAppMeta :one
INSERT INTO app_meta (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    updated_at = now()
RETURNING key, value, updated_at
`

type SetAppMetaParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetAppMeta(ctx context.Context, arg SetAppMetaParams) (AppMeta, error) {
	row := q.db.QueryRow(ctx, setAppMeta, arg.Key, arg.Value)
	var i AppMeta
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
