// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const bulkUpdateEnvironmentOrder = `-- name: BulkUpdateEnvironmentOrder :exec
UPDATE environments
SET sort_order = (ordered.position - 1)::int
FROM unnest($2::uuid[]) WITH ORDINALITY AS ordered(id, position)
WHERE environments.id = ordered.id
  AND environments.project_id = $1
`

type BulkUpdateEnvironmentOrderParams struct {
	ProjectID      uuid.UUID   `json:"project_id"`
	EnvironmentIds []uuid.UUID `json:"environment_ids"`
}

// Position in the array becomes sort_order, 0-based.
func (q *Queries) BulkUpdateEnvironmentOrder(ctx context.Context, arg BulkUpdateEnvironmentOrderParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateEnvironmentOrder, arg.ProjectID, arg.EnvironmentIds)
	return err
}

const bulkUpdateVariableOrder = `-- name: BulkUpdateVariableOrder :exec
UPDATE environment_variables
SET sort_order = (ordered.position - 1)::int
FROM unnest($2::uuid[]) WITH ORDINALITY AS ordered(id, position)
WHERE environment_variables.id = ordered.id
  AND environment_variables.environment_id = $1
`

type BulkUpdateVariableOrderParams struct {
	EnvironmentID uuid.UUID   `json:"environment_id"`
	VariableIds   []uuid.UUID `json:"variable_ids"`
}

// Position in the array becomes sort_order, 0-based.
func (q *Queries) BulkUpdateVariableOrder(ctx context.Context, arg BulkUpdateVariableOrderParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateVariableOrder, arg.EnvironmentID, arg.VariableIds)
	return err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (project_id, name, sort_order)
VALUES (
    $1,
    $2,
    (
        SELECT COALESCE(MAX(existing.sort_order) + 1, 0)::int
        FROM environments AS existing
        WHERE existing.project_id = $1
    )
)
RETURNING id, project_id, name, sort_order, created_at
`

type CreateEnvironmentParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Name      string    `json:"name"`
}

// Appends the environment after the project's others, 0-based. Concurrent
// creates may pick the same sort_order, which is harmless: ties fall back to
// created_at.
func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment, arg.ProjectID, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createVariable = `-- name: CreateVariable :one
INSERT INTO environment_variables (environment_id, key, type, value, sort_order)
VALUES (
    $1,
    $2,
    $3,
    $4,
    (
        SELECT COALESCE(MAX(existing.sort_order) + 1, 0)::int
        FROM environment_variables AS existing
        WHERE existing.environment_id = $1
    )
)
RETURNING id, environment_id, key, type, value, sort_order, created_at
`

type CreateVariableParams struct {
	EnvironmentID uuid.UUID `json:"environment_id"`
	Key           string    `json:"key"`
	Type          string    `json:"type"`
	Value         *string   `json:"value"`
}

// Appends the variable after the environment's others, 0-based. The caller has
// already refused a secret with a value; the table's CHECK refuses it again.
func (q *Queries) CreateVariable(ctx context.Context, arg CreateVariableParams) (EnvironmentVariable, error) {
	row := q.db.QueryRow(ctx, createVariable,
		arg.EnvironmentID,
		arg.Key,
		arg.Type,
		arg.Value,
	)
	var i EnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.Type,
		&i.Value,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
DELETE FROM environments
WHERE id = $1
`

// Variables go with it via ON DELETE CASCADE.
func (q *Queries) DeleteEnvironment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironment, id)
	return err
}

const deleteVariable = `-- name: DeleteVariable :exec
DELETE FROM environment_variables
WHERE id = $1
`

func (q *Queries) DeleteVariable(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariable, id)
	return err
}

const getEnvironmentByID = `-- name: GetEnvironmentByID :one
SELECT id, project_id, name, sort_order, created_at
FROM environments
WHERE id = $1
`

func (q *Queries) GetEnvironmentByID(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByID, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getVariableByID = `-- name: GetVariableByID :one
SELECT id, environment_id, key, type, value, sort_order, created_at
FROM environment_variables
WHERE id = $1
`

func (q *Queries) GetVariableByID(ctx context.Context, id uuid.UUID) (EnvironmentVariable, error) {
	row := q.db.QueryRow(ctx, getVariableByID, id)
	var i EnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.Type,
		&i.Value,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listEnvironmentIDsForUpdate = `-- name: ListEnvironmentIDsForUpdate :many
SELECT id
FROM environments
WHERE project_id = $1
ORDER BY sort_order, created_at
FOR UPDATE
`

// Locked, so a reorder validates and writes against the same set.
func (q *Queries) ListEnvironmentIDsForUpdate(ctx context.Context, projectID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listEnvironmentIDsForUpdate, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsByProject = `-- name: ListEnvironmentsByProject :many
SELECT id, project_id, name, sort_order, created_at
FROM environments
WHERE project_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListEnvironmentsByProject(ctx context.Context, projectID uuid.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariableIDsForUpdate = `-- name: ListVariableIDsForUpdate :many
SELECT id
FROM environment_variables
WHERE environment_id = $1
ORDER BY sort_order, created_at
FOR UPDATE
`

// Locked, so a reorder validates and writes against the same set.
func (q *Queries) ListVariableIDsForUpdate(ctx context.Context, environmentID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listVariableIDsForUpdate, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariablesByEnvironment = `-- name: ListVariablesByEnvironment :many
SELECT id, environment_id, key, type, value, sort_order, created_at
FROM environment_variables
WHERE environment_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListVariablesByEnvironment(ctx context.Context, environmentID uuid.UUID) ([]EnvironmentVariable, error) {
	rows, err := q.db.Query(ctx, listVariablesByEnvironment, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentVariable{}
	for rows.Next() {
		var i EnvironmentVariable
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Key,
			&i.Type,
			&i.Value,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironmentName = `-- name: UpdateEnvironmentName :one
UPDATE environments
SET name = $2
WHERE id = $1
RETURNING id, project_id, name, sort_order, created_at
`

type UpdateEnvironmentNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateEnvironmentName(ctx context.Context, arg UpdateEnvironmentNameParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironmentName, arg.ID, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const updateVariable = `-- name: UpdateVariable :one
UPDATE environment_variables
SET key = COALESCE($1, key),
    type = COALESCE($2, type),
    value = CASE
        WHEN COALESCE($2, type) = 'secret' THEN NULL
        WHEN $3::boolean THEN $4
        ELSE value
    END
WHERE id = $5
RETURNING id, environment_id, key, type, value, sort_order, created_at
`

type UpdateVariableParams struct {
	Key      *string   `json:"key"`
	Type     *string   `json:"type"`
	SetValue bool      `json:"set_value"`
	Value    *string   `json:"value"`
	ID       uuid.UUID `json:"id"`
}

// A partial update merged in SQL, so it is atomic against concurrent edits.
// NULL key or type keeps the current one. value is only written when
// set_value is true, since null is itself a valid new value.
//
// Whatever the request says, a variable that ends up secret ends up with no
// value: that is how a regular -> secret change clears the stored value.
func (q *Queries) UpdateVariable(ctx context.Context, arg UpdateVariableParams) (EnvironmentVariable, error) {
	row := q.db.QueryRow(ctx, updateVariable,
		arg.Key,
		arg.Type,
		arg.SetValue,
		arg.Value,
		arg.ID,
	)
	var i EnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Key,
		&i.Type,
		&i.Value,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
