// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const bulkUpdateFolderOrder = `-- name: BulkUpdateFolderOrder :exec
UPDATE folders
SET sort_order = ordered.position::int
FROM unnest($3::uuid[]) WITH ORDINALITY AS ordered(id, position)
WHERE folders.id = ordered.id
  AND folders.project_id = $1
  AND folders.parent_id IS NOT DISTINCT FROM $2
`

type BulkUpdateFolderOrderParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	ParentID  *uuid.UUID  `json:"parent_id"`
	FolderIds []uuid.UUID `json:"folder_ids"`
}

// Position in the array becomes sort_order, within one parent only.
func (q *Queries) BulkUpdateFolderOrder(ctx context.Context, arg BulkUpdateFolderOrderParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateFolderOrder, arg.ProjectID, arg.ParentID, arg.FolderIds)
	return err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (project_id, parent_id, name, sort_order)
VALUES (
    $1,
    $2,
    $3,
    (
        SELECT COALESCE(MAX(siblings.sort_order) + 1, 0)::int
        FROM folders AS siblings
        WHERE siblings.project_id = $1
          AND siblings.parent_id IS NOT DISTINCT FROM $2
    )
)
RETURNING id, project_id, parent_id, name, sort_order, created_at
`

type CreateFolderParams struct {
	ProjectID uuid.UUID  `json:"project_id"`
	ParentID  *uuid.UUID `json:"parent_id"`
	Name      string     `json:"name"`
}

// Appends the folder after its siblings: the folders sharing its project and
// parent. parent_id is NULL at the root, so sibling filters here and below
// compare it with IS NOT DISTINCT FROM. Concurrent creates may pick the same
// sort_order, which is harmless: ties fall back to created_at.
func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder, arg.ProjectID, arg.ParentID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders
WHERE id = $1
`

// The subtree goes with it via ON DELETE CASCADE on parent_id.
func (q *Queries) DeleteFolder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFolder, id)
	return err
}

const getFolderByID = `-- name: GetFolderByID :one
SELECT id, project_id, parent_id, name, sort_order, created_at
FROM folders
WHERE id = $1
`

func (q *Queries) GetFolderByID(ctx context.Context, id uuid.UUID) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const isDescendant = `-- name: IsDescendant :one
WITH RECURSIVE ancestors AS (
    SELECT folders.id, folders.parent_id
    FROM folders
    WHERE folders.id = $2::uuid

    UNION

    SELECT parent.id, parent.parent_id
    FROM folders AS parent
    JOIN ancestors ON parent.id = ancestors.parent_id
)
SELECT EXISTS (
    SELECT 1 FROM ancestors WHERE ancestors.id = $1::uuid
) AS is_descendant
`

type IsDescendantParams struct {
	RootID   uuid.UUID `json:"root_id"`
	FolderID uuid.UUID `json:"folder_id"`
}

// Reports whether folder_id lies in the subtree rooted at root_id, counting
// root_id itself. Walks up from folder_id, so the cost is the depth of the
// tree rather than the size of the subtree. UNION rather than UNION ALL, so
// the walk terminates even if a cycle ever slipped in.
func (q *Queries) IsDescendant(ctx context.Context, arg IsDescendantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isDescendant, arg.RootID, arg.FolderID)
	var is_descendant bool
	err := row.Scan(&is_descendant)
	return is_descendant, err
}

const listFoldersByProject = `-- name: ListFoldersByProject :many
SELECT id, project_id, parent_id, name, sort_order, created_at
FROM folders
WHERE project_id = $1
ORDER BY parent_id NULLS FIRST, sort_order, created_at
`

// Every folder of the project in one flat list; the client builds the tree.
func (q *Queries) ListFoldersByProject(ctx context.Context, projectID uuid.UUID) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ParentID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiblingFolderIDs = `-- name: ListSiblingFolderIDs :many
SELECT id
FROM folders
WHERE project_id = $1
  AND parent_id IS NOT DISTINCT FROM $2
ORDER BY sort_order, created_at
FOR UPDATE
`

type ListSiblingFolderIDsParams struct {
	ProjectID uuid.UUID  `json:"project_id"`
	ParentID  *uuid.UUID `json:"parent_id"`
}

// Locked, so a reorder validates and writes against the same sibling set.
func (q *Queries) ListSiblingFolderIDs(ctx context.Context, arg ListSiblingFolderIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSiblingFolderIDs, arg.ProjectID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProjectFolders = `-- name: LockProjectFolders :exec
SELECT id
FROM projects
WHERE id = $1
FOR NO KEY UPDATE
`

// Serialises tree changes within one project, so two concurrent moves cannot
// each pass the cycle check and together create a cycle. NO KEY UPDATE does
// not block the key-share locks taken by inserts referencing the project.
func (q *Queries) LockProjectFolders(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockProjectFolders, id)
	return err
}

const updateFolderName = `-- name: UpdateFolderName :one
UPDATE folders
SET name = $2
WHERE id = $1
RETURNING id, project_id, parent_id, name, sort_order, created_at
`

type UpdateFolderNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateFolderName(ctx context.Context, arg UpdateFolderNameParams) (Folder, error) {
	row := q.db.QueryRow(ctx, updateFolderName, arg.ID, arg.Name)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const updateFolderParent = `-- name: UpdateFolderParent :one
UPDATE folders
SET parent_id = $1,
    sort_order = COALESCE(
        $2::int,
        (
            SELECT COALESCE(MAX(siblings.sort_order) + 1, 0)::int
            FROM folders AS siblings
            WHERE siblings.project_id = folders.project_id
              AND siblings.parent_id IS NOT DISTINCT FROM $1
              AND siblings.id <> folders.id
        )
    )
WHERE folders.id = $3
RETURNING id, project_id, parent_id, name, sort_order, created_at
`

type UpdateFolderParentParams struct {
	ParentID  *uuid.UUID `json:"parent_id"`
	SortOrder *int32     `json:"sort_order"`
	ID        uuid.UUID  `json:"id"`
}

// Without an explicit sort_order the folder goes after its new siblings. The
// folder itself is excluded so that a move within the same parent does not
// count its own position.
func (q *Queries) UpdateFolderParent(ctx context.Context, arg UpdateFolderParentParams) (Folder, error) {
	row := q.db.QueryRow(ctx, updateFolderParent, arg.ParentID, arg.SortOrder, arg.ID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ParentID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
