// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO team_invitations (team_id, email, invited_by)
VALUES ($1, $2, $3)
RETURNING id, team_id, email, invited_by, status, created_at, responded_at
`

type CreateInvitationParams struct {
	TeamID    uuid.UUID `json:"team_id"`
	Email     string    `json:"email"`
	InvitedBy uuid.UUID `json:"invited_by"`
}

// Duplicate pending invitations are caught by the partial unique index rather
// than by a pre-SELECT, which would race.
func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (TeamInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation, arg.TeamID, arg.Email, arg.InvitedBy)
	var i TeamInvitation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM team_invitations
WHERE id = $1
`

func (q *Queries) DeleteInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvitation, id)
	return err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, team_id, email, invited_by, status, created_at, responded_at
FROM team_invitations
WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id uuid.UUID) (TeamInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i TeamInvitation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const isEmailTeamMember = `-- name: IsEmailTeamMember :one
SELECT EXISTS (
    SELECT 1
    FROM team_members
    JOIN users ON users.id = team_members.user_id
    WHERE team_members.team_id = $1
      AND users.email = $2
) AS is_member
`

type IsEmailTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	Email  string    `json:"email"`
}

func (q *Queries) IsEmailTeamMember(ctx context.Context, arg IsEmailTeamMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isEmailTeamMember, arg.TeamID, arg.Email)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const listPendingInvitationsForEmail = `-- name: ListPendingInvitationsForEmail :many
SELECT
    team_invitations.id,
    team_invitations.created_at,
    teams.id   AS team_id,
    teams.name AS team_name,
    inviter.name  AS inviter_name,
    inviter.email AS inviter_email
FROM team_invitations
JOIN teams ON teams.id = team_invitations.team_id
JOIN users AS inviter ON inviter.id = team_invitations.invited_by
WHERE team_invitations.email = $1
  AND team_invitations.status = 'pending'
ORDER BY team_invitations.created_at
`

type ListPendingInvitationsForEmailRow struct {
	ID           uuid.UUID `json:"id"`
	CreatedAt    time.Time `json:"created_at"`
	TeamID       uuid.UUID `json:"team_id"`
	TeamName     string    `json:"team_name"`
	InviterName  string    `json:"inviter_name"`
	InviterEmail string    `json:"inviter_email"`
}

func (q *Queries) ListPendingInvitationsForEmail(ctx context.Context, email string) ([]ListPendingInvitationsForEmailRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsForEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitationsForEmailRow{}
	for rows.Next() {
		var i ListPendingInvitationsForEmailRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.TeamID,
			&i.TeamName,
			&i.InviterName,
			&i.InviterEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsForTeam = `-- name: ListPendingInvitationsForTeam :many
SELECT id, email, created_at
FROM team_invitations
WHERE team_id = $1
  AND status = 'pending'
ORDER BY created_at
`

type ListPendingInvitationsForTeamRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListPendingInvitationsForTeam(ctx context.Context, teamID uuid.UUID) ([]ListPendingInvitationsForTeamRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsForTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitationsForTeamRow{}
	for rows.Next() {
		var i ListPendingInvitationsForTeamRow
		if err := rows.Scan(&i.ID, &i.Email, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvitationStatus = `-- name: UpdateInvitationStatus :one
UPDATE team_invitations
SET status = $2,
    responded_at = now()
WHERE id = $1
  AND status = 'pending'
RETURNING id, team_id, email, invited_by, status, created_at, responded_at
`

type UpdateInvitationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// The status guard makes responding idempotent under concurrency: a second
// accept or reject matches no row instead of overwriting the first answer.
func (q *Queries) UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) (TeamInvitation, error) {
	row := q.db.QueryRow(ctx, updateInvitationStatus, arg.ID, arg.Status)
	var i TeamInvitation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Email,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}
