// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const bulkUpdateProjectOrder = `-- name: BulkUpdateProjectOrder :exec
UPDATE projects
SET sort_order = ordered.position::int
FROM unnest($2::uuid[]) WITH ORDINALITY AS ordered(id, position)
WHERE projects.id = ordered.id
  AND projects.team_id = $1
`

type BulkUpdateProjectOrderParams struct {
	TeamID     uuid.UUID   `json:"team_id"`
	ProjectIds []uuid.UUID `json:"project_ids"`
}

// Position in the array becomes sort_order. One statement, so the new order
// lands atomically without an explicit transaction.
func (q *Queries) BulkUpdateProjectOrder(ctx context.Context, arg BulkUpdateProjectOrderParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateProjectOrder, arg.TeamID, arg.ProjectIds)
	return err
}

const countProjectsInTeam = `-- name: CountProjectsInTeam :one
SELECT count(*)
FROM projects
WHERE team_id = $1
  AND id = ANY($2::uuid[])
`

type CountProjectsInTeamParams struct {
	TeamID     uuid.UUID   `json:"team_id"`
	ProjectIds []uuid.UUID `json:"project_ids"`
}

// Used to reject project ids that belong to a different team.
func (q *Queries) CountProjectsInTeam(ctx context.Context, arg CountProjectsInTeamParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsInTeam, arg.TeamID, arg.ProjectIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (team_id, name, owner_id, sort_order)
VALUES (
    $1,
    $2,
    $3,
    COALESCE((SELECT max(sort_order) + 1 FROM projects WHERE team_id = $1), 0)
)
RETURNING id, team_id, name, owner_id, sort_order, created_at
`

type CreateProjectParams struct {
	TeamID  uuid.UUID `json:"team_id"`
	Name    string    `json:"name"`
	OwnerID uuid.UUID `json:"owner_id"`
}

// sort_order is computed in the statement so two clients creating projects at
// once cannot both read the same "max" and then both write it.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.TeamID, arg.Name, arg.OwnerID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.OwnerID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = $1
`

// project_access rows go with it via ON DELETE CASCADE.
func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, team_id, name, owner_id, sort_order, created_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.OwnerID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectForUser = `-- name: GetProjectForUser :one
SELECT
    projects.id, projects.team_id, projects.name, projects.owner_id, projects.sort_order, projects.created_at,
    teams.owner_id AS team_owner_id
FROM projects
JOIN teams ON teams.id = projects.team_id
JOIN team_members
  ON team_members.team_id = projects.team_id
 AND team_members.user_id = $1
WHERE projects.id = $2
  AND (
        team_members.all_projects
     OR teams.owner_id = $1
     OR projects.owner_id = $1
     OR EXISTS (
            SELECT 1
            FROM project_access
            WHERE project_access.project_id = projects.id
              AND project_access.user_id = $1
        )
  )
`

type GetProjectForUserParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

type GetProjectForUserRow struct {
	Project     Project   `json:"project"`
	TeamOwnerID uuid.UUID `json:"team_owner_id"`
}

// The whole access rule in one query: the user must be a member of the
// project's team, and then either see everything, own the team, own the
// project, or hold an explicit grant. No row means "no access", which callers
// answer with 404 — a user who cannot reach a project must not learn it exists.
//
// The team's owner rides along because every caller that needs access also
// needs to know whether this user may modify the project, and comparing two
// ids in Go beats a computed column that sqlc can only type as nullable.
func (q *Queries) GetProjectForUser(ctx context.Context, arg GetProjectForUserParams) (GetProjectForUserRow, error) {
	row := q.db.QueryRow(ctx, getProjectForUser, arg.UserID, arg.ProjectID)
	var i GetProjectForUserRow
	err := row.Scan(
		&i.Project.ID,
		&i.Project.TeamID,
		&i.Project.Name,
		&i.Project.OwnerID,
		&i.Project.SortOrder,
		&i.Project.CreatedAt,
		&i.TeamOwnerID,
	)
	return i, err
}

const listAccessibleProjects = `-- name: ListAccessibleProjects :many
SELECT projects.id, projects.team_id, projects.name, projects.owner_id, projects.sort_order, projects.created_at
FROM projects
JOIN teams ON teams.id = projects.team_id
JOIN team_members
  ON team_members.team_id = projects.team_id
 AND team_members.user_id = $1
WHERE projects.team_id = $2
  AND (
        team_members.all_projects
     OR teams.owner_id = $1
     OR projects.owner_id = $1
     OR EXISTS (
            SELECT 1
            FROM project_access
            WHERE project_access.project_id = projects.id
              AND project_access.user_id = $1
        )
  )
ORDER BY projects.sort_order, projects.created_at
`

type ListAccessibleProjectsParams struct {
	UserID uuid.UUID `json:"user_id"`
	TeamID uuid.UUID `json:"team_id"`
}

type ListAccessibleProjectsRow struct {
	Project Project `json:"project"`
}

// Same rule as GetProjectForUser, applied across one team.
func (q *Queries) ListAccessibleProjects(ctx context.Context, arg ListAccessibleProjectsParams) ([]ListAccessibleProjectsRow, error) {
	rows, err := q.db.Query(ctx, listAccessibleProjects, arg.UserID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessibleProjectsRow{}
	for rows.Next() {
		var i ListAccessibleProjectsRow
		if err := rows.Scan(
			&i.Project.ID,
			&i.Project.TeamID,
			&i.Project.Name,
			&i.Project.OwnerID,
			&i.Project.SortOrder,
			&i.Project.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamProjectIDs = `-- name: ListTeamProjectIDs :many
SELECT id
FROM projects
WHERE team_id = $1
`

// Every project in the team, access ignored: reordering is a team-wide
// operation and the caller must account for all of them.
func (q *Queries) ListTeamProjectIDs(ctx context.Context, teamID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTeamProjectIDs, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectName = `-- name: UpdateProjectName :one
UPDATE projects
SET name = $2
WHERE id = $1
RETURNING id, team_id, name, owner_id, sort_order, created_at
`

type UpdateProjectNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectName, arg.ID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.OwnerID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
