// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_access.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countTeamMembersInList = `-- name: CountTeamMembersInList :one
SELECT count(*)
FROM team_members
WHERE team_id = $1
  AND user_id = ANY($2::uuid[])
`

type CountTeamMembersInListParams struct {
	TeamID  uuid.UUID   `json:"team_id"`
	UserIds []uuid.UUID `json:"user_ids"`
}

// Used to reject user ids that are not members of the team.
func (q *Queries) CountTeamMembersInList(ctx context.Context, arg CountTeamMembersInListParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamMembersInList, arg.TeamID, arg.UserIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllProjectAccess = `-- name: DeleteAllProjectAccess :exec
DELETE FROM project_access
WHERE project_id = $1
`

func (q *Queries) DeleteAllProjectAccess(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllProjectAccess, projectID)
	return err
}

const deleteAllUserAccessInTeam = `-- name: DeleteAllUserAccessInTeam :exec
DELETE FROM project_access
USING projects
WHERE project_access.project_id = projects.id
  AND project_access.user_id = $1
  AND projects.team_id = $2
`

type DeleteAllUserAccessInTeamParams struct {
	UserID uuid.UUID `json:"user_id"`
	TeamID uuid.UUID `json:"team_id"`
}

// Clears one user's explicit grants within a single team, leaving grants in
// other teams untouched.
func (q *Queries) DeleteAllUserAccessInTeam(ctx context.Context, arg DeleteAllUserAccessInTeamParams) error {
	_, err := q.db.Exec(ctx, deleteAllUserAccessInTeam, arg.UserID, arg.TeamID)
	return err
}

const grantProjectAccess = `-- name: GrantProjectAccess :exec
INSERT INTO project_access (project_id, user_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT (project_id, user_id) DO NOTHING
`

type GrantProjectAccessParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	UserIds   []uuid.UUID `json:"user_ids"`
}

// Bulk grant for one project. Already-granted users are left alone rather than
// raising a conflict.
func (q *Queries) GrantProjectAccess(ctx context.Context, arg GrantProjectAccessParams) error {
	_, err := q.db.Exec(ctx, grantProjectAccess, arg.ProjectID, arg.UserIds)
	return err
}

const grantUserProjectAccess = `-- name: GrantUserProjectAccess :exec
INSERT INTO project_access (project_id, user_id)
SELECT unnest($1::uuid[]), $2
ON CONFLICT (project_id, user_id) DO NOTHING
`

type GrantUserProjectAccessParams struct {
	ProjectIds []uuid.UUID `json:"project_ids"`
	UserID     uuid.UUID   `json:"user_id"`
}

// Bulk grant for one user across several projects: the same table seen from
// the member side.
func (q *Queries) GrantUserProjectAccess(ctx context.Context, arg GrantUserProjectAccessParams) error {
	_, err := q.db.Exec(ctx, grantUserProjectAccess, arg.ProjectIds, arg.UserID)
	return err
}

const listProjectAccessUsers = `-- name: ListProjectAccessUsers :many
SELECT project_access.user_id, users.email, users.name
FROM project_access
JOIN users ON users.id = project_access.user_id
WHERE project_access.project_id = $1
ORDER BY users.email
`

type ListProjectAccessUsersRow struct {
	UserID uuid.UUID `json:"user_id"`
	Email  string    `json:"email"`
	Name   string    `json:"name"`
}

func (q *Queries) ListProjectAccessUsers(ctx context.Context, projectID uuid.UUID) ([]ListProjectAccessUsersRow, error) {
	rows, err := q.db.Query(ctx, listProjectAccessUsers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectAccessUsersRow{}
	for rows.Next() {
		var i ListProjectAccessUsersRow
		if err := rows.Scan(&i.UserID, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAccessibleProjectIDs = `-- name: ListUserAccessibleProjectIDs :many
SELECT project_access.project_id
FROM project_access
JOIN projects ON projects.id = project_access.project_id
WHERE project_access.user_id = $1
  AND projects.team_id = $2
ORDER BY projects.sort_order, projects.created_at
`

type ListUserAccessibleProjectIDsParams struct {
	UserID uuid.UUID `json:"user_id"`
	TeamID uuid.UUID `json:"team_id"`
}

// The explicit grant list only: projects this user reaches through
// all_projects, team ownership or project ownership are not included.
func (q *Queries) ListUserAccessibleProjectIDs(ctx context.Context, arg ListUserAccessibleProjectIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserAccessibleProjectIDs, arg.UserID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var project_id uuid.UUID
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberAllProjects = `-- name: UpdateMemberAllProjects :one
UPDATE team_members
SET all_projects = $1
WHERE team_id = $2
  AND user_id = $3
RETURNING team_id, user_id, all_projects, created_at
`

type UpdateMemberAllProjectsParams struct {
	AllProjects bool      `json:"all_projects"`
	TeamID      uuid.UUID `json:"team_id"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateMemberAllProjects(ctx context.Context, arg UpdateMemberAllProjectsParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, updateMemberAllProjects, arg.AllProjects, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.AllProjects,
		&i.CreatedAt,
	)
	return i, err
}
