// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const bulkUpdateRequestOrder = `-- name: BulkUpdateRequestOrder :exec
UPDATE requests
SET sort_order = (ordered.position - 1)::int
FROM unnest($3::uuid[]) WITH ORDINALITY AS ordered(id, position)
WHERE requests.id = ordered.id
  AND requests.project_id = $1
  AND requests.folder_id IS NOT DISTINCT FROM $2
`

type BulkUpdateRequestOrderParams struct {
	ProjectID  uuid.UUID   `json:"project_id"`
	FolderID   *uuid.UUID  `json:"folder_id"`
	RequestIds []uuid.UUID `json:"request_ids"`
}

// Position in the array becomes sort_order, 0-based, within one folder scope.
func (q *Queries) BulkUpdateRequestOrder(ctx context.Context, arg BulkUpdateRequestOrderParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateRequestOrder, arg.ProjectID, arg.FolderID, arg.RequestIds)
	return err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (project_id, folder_id, name, method, url, sort_order)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    (
        SELECT COALESCE(MAX(siblings.sort_order) + 1, 0)::int
        FROM requests AS siblings
        WHERE siblings.project_id = $1
          AND siblings.folder_id IS NOT DISTINCT FROM $2
    )
)
RETURNING id, project_id, folder_id, name, method, url, headers, query_params, body, sort_order, created_at, updated_at
`

type CreateRequestParams struct {
	ProjectID uuid.UUID  `json:"project_id"`
	FolderID  *uuid.UUID `json:"folder_id"`
	Name      string     `json:"name"`
	Method    string     `json:"method"`
	Url       string     `json:"url"`
}

// Appends the request after its siblings: the requests sharing its project
// and folder, 0-based. folder_id is NULL at the root, so sibling filters here
// and below compare it with IS NOT DISTINCT FROM. Concurrent creates may pick
// the same sort_order, which is harmless: ties fall back to created_at.
func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.ProjectID,
		arg.FolderID,
		arg.Name,
		arg.Method,
		arg.Url,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.QueryParams,
		&i.Body,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRequest = `-- name: DeleteRequest :exec
DELETE FROM requests
WHERE id = $1
`

func (q *Queries) DeleteRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRequest, id)
	return err
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT id, project_id, folder_id, name, method, url, headers, query_params, body, sort_order, created_at, updated_at
FROM requests
WHERE id = $1
`

func (q *Queries) GetRequestByID(ctx context.Context, id uuid.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.QueryParams,
		&i.Body,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRequestsByProject = `-- name: ListRequestsByProject :many
SELECT id, project_id, folder_id, name, method, url, sort_order, created_at, updated_at
FROM requests
WHERE project_id = $1
ORDER BY folder_id NULLS FIRST, sort_order, created_at
`

type ListRequestsByProjectRow struct {
	ID        uuid.UUID  `json:"id"`
	ProjectID uuid.UUID  `json:"project_id"`
	FolderID  *uuid.UUID `json:"folder_id"`
	Name      string     `json:"name"`
	Method    string     `json:"method"`
	Url       string     `json:"url"`
	SortOrder int32      `json:"sort_order"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// Every request of the project in one flat list, without headers, query
// parameters or body; the client places them in the folder tree.
func (q *Queries) ListRequestsByProject(ctx context.Context, projectID uuid.UUID) ([]ListRequestsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listRequestsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestsByProjectRow{}
	for rows.Next() {
		var i ListRequestsByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FolderID,
			&i.Name,
			&i.Method,
			&i.Url,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiblingRequestIDs = `-- name: ListSiblingRequestIDs :many
SELECT id
FROM requests
WHERE project_id = $1
  AND folder_id IS NOT DISTINCT FROM $2
ORDER BY sort_order, created_at
FOR UPDATE
`

type ListSiblingRequestIDsParams struct {
	ProjectID uuid.UUID  `json:"project_id"`
	FolderID  *uuid.UUID `json:"folder_id"`
}

// Locked, so a reorder validates and writes against the same sibling set.
func (q *Queries) ListSiblingRequestIDs(ctx context.Context, arg ListSiblingRequestIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSiblingRequestIDs, arg.ProjectID, arg.FolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequest = `-- name: UpdateRequest :one
UPDATE requests
SET name = COALESCE($1, name),
    method = COALESCE($2, method),
    url = COALESCE($3, url),
    headers = COALESCE($4::jsonb, headers),
    query_params = COALESCE($5::jsonb, query_params),
    body = COALESCE($6::jsonb, body),
    updated_at = now()
WHERE id = $7
RETURNING id, project_id, folder_id, name, method, url, headers, query_params, body, sort_order, created_at, updated_at
`

type UpdateRequestParams struct {
	Name        *string         `json:"name"`
	Method      *string         `json:"method"`
	Url         *string         `json:"url"`
	Headers     json.RawMessage `json:"headers"`
	QueryParams json.RawMessage `json:"query_params"`
	Body        json.RawMessage `json:"body"`
	ID          uuid.UUID       `json:"id"`
}

// A partial update merged in SQL, so it is atomic against concurrent edits:
// NULL keeps the current value. An empty url is a real value, not "keep".
// headers, query_params and body each replace the whole value; the caller has
// already validated and normalised them.
func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, updateRequest,
		arg.Name,
		arg.Method,
		arg.Url,
		arg.Headers,
		arg.QueryParams,
		arg.Body,
		arg.ID,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.QueryParams,
		&i.Body,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRequestFolder = `-- name: UpdateRequestFolder :one
UPDATE requests
SET folder_id = $1,
    sort_order = COALESCE(
        $2::int,
        (
            SELECT COALESCE(MAX(siblings.sort_order) + 1, 0)::int
            FROM requests AS siblings
            WHERE siblings.project_id = requests.project_id
              AND siblings.folder_id IS NOT DISTINCT FROM $1
              AND siblings.id <> requests.id
        )
    ),
    updated_at = now()
WHERE requests.id = $3
RETURNING id, project_id, folder_id, name, method, url, headers, query_params, body, sort_order, created_at, updated_at
`

type UpdateRequestFolderParams struct {
	FolderID  *uuid.UUID `json:"folder_id"`
	SortOrder *int32     `json:"sort_order"`
	ID        uuid.UUID  `json:"id"`
}

// Without an explicit sort_order the request goes after its new siblings. The
// request itself is excluded so that a move within the same folder does not
// count its own position.
func (q *Queries) UpdateRequestFolder(ctx context.Context, arg UpdateRequestFolderParams) (Request, error) {
	row := q.db.QueryRow(ctx, updateRequestFolder, arg.FolderID, arg.SortOrder, arg.ID)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FolderID,
		&i.Name,
		&i.Method,
		&i.Url,
		&i.Headers,
		&i.QueryParams,
		&i.Body,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
