// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id, created_at
`

type CreateTeamParams struct {
	Name    string    `json:"name"`
	OwnerID uuid.UUID `json:"owner_id"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.Name, arg.OwnerID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const createTeamMember = `-- name: CreateTeamMember :one
INSERT INTO team_members (team_id, user_id, all_projects)
VALUES ($1, $2, $3)
RETURNING team_id, user_id, all_projects, created_at
`

type CreateTeamMemberParams struct {
	TeamID      uuid.UUID `json:"team_id"`
	UserID      uuid.UUID `json:"user_id"`
	AllProjects bool      `json:"all_projects"`
}

func (q *Queries) CreateTeamMember(ctx context.Context, arg CreateTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, createTeamMember, arg.TeamID, arg.UserID, arg.AllProjects)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.AllProjects,
		&i.CreatedAt,
	)
	return i, err
}

const createTeamMemberIfAbsent = `-- name: CreateTeamMemberIfAbsent :exec
INSERT INTO team_members (team_id, user_id, all_projects)
VALUES ($1, $2, true)
ON CONFLICT (team_id, user_id) DO NOTHING
`

type CreateTeamMemberIfAbsentParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

// Used when accepting an invitation: an already-present membership must not
// turn the acceptance into an error.
func (q *Queries) CreateTeamMemberIfAbsent(ctx context.Context, arg CreateTeamMemberIfAbsentParams) error {
	_, err := q.db.Exec(ctx, createTeamMemberIfAbsent, arg.TeamID, arg.UserID)
	return err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams
WHERE id = $1
`

// Memberships go with it via ON DELETE CASCADE.
func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const deleteTeamMember = `-- name: DeleteTeamMember :execrows
DELETE FROM team_members
WHERE team_id = $1
  AND user_id = $2
`

type DeleteTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

// Returns the number of rows removed so callers can tell "removed" from
// "was never a member".
func (q *Queries) DeleteTeamMember(ctx context.Context, arg DeleteTeamMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTeamMember, arg.TeamID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, owner_id, created_at
FROM teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamMember = `-- name: GetTeamMember :one
SELECT team_id, user_id, all_projects, created_at
FROM team_members
WHERE team_id = $1
  AND user_id = $2
`

type GetTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTeamMember(ctx context.Context, arg GetTeamMemberParams) (TeamMember, error) {
	row := q.db.QueryRow(ctx, getTeamMember, arg.TeamID, arg.UserID)
	var i TeamMember
	err := row.Scan(
		&i.TeamID,
		&i.UserID,
		&i.AllProjects,
		&i.CreatedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT team_members.user_id, users.email, users.name, team_members.all_projects
FROM team_members
JOIN users ON users.id = team_members.user_id
WHERE team_members.team_id = $1
ORDER BY users.email
`

type ListTeamMembersRow struct {
	UserID      uuid.UUID `json:"user_id"`
	Email       string    `json:"email"`
	Name        string    `json:"name"`
	AllProjects bool      `json:"all_projects"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID uuid.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.AllProjects,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsForUser = `-- name: ListTeamsForUser :many
SELECT teams.id, teams.name, teams.owner_id, teams.created_at, count(all_members.user_id) AS member_count
FROM teams
JOIN team_members AS my_membership
  ON my_membership.team_id = teams.id
 AND my_membership.user_id = $1
JOIN team_members AS all_members
  ON all_members.team_id = teams.id
GROUP BY teams.id
ORDER BY teams.created_at
`

type ListTeamsForUserRow struct {
	Team        Team  `json:"team"`
	MemberCount int64 `json:"member_count"`
}

// Teams this user belongs to, with the size of each team. The second join is
// what counts members; the first is what filters to this user's teams.
func (q *Queries) ListTeamsForUser(ctx context.Context, userID uuid.UUID) ([]ListTeamsForUserRow, error) {
	rows, err := q.db.Query(ctx, listTeamsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsForUserRow{}
	for rows.Next() {
		var i ListTeamsForUserRow
		if err := rows.Scan(
			&i.Team.ID,
			&i.Team.Name,
			&i.Team.OwnerID,
			&i.Team.CreatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeamName = `-- name: UpdateTeamName :one
UPDATE teams
SET name = $2
WHERE id = $1
RETURNING id, name, owner_id, created_at
`

type UpdateTeamNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateTeamName(ctx context.Context, arg UpdateTeamNameParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeamName, arg.ID, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}
